-- ============================================
-- RESET COMPLETO PRE-TESTE
-- Cola no Supabase SQL Editor e corre
-- Duas fases: 1) limpa TODAS as tabelas primeiro, 2) restaura TODAS a seguir.
-- (Fazer numa tabela de cada vez causava CASCADE a apagar tabelas ja restauradas.)
-- ============================================

SET session_replication_role = replica;

-- FASE 1: limpar tudo
TRUNCATE TABLE box_scores CASCADE;
TRUNCATE TABLE play_by_play CASCADE;
TRUNCATE TABLE games CASCADE;
TRUNCATE TABLE preseason_games CASCADE;
TRUNCATE TABLE summer_league_rosters CASCADE;
TRUNCATE TABLE summer_league_games CASCADE;
TRUNCATE TABLE summer_league_box_scores CASCADE;
TRUNCATE TABLE player_stats CASCADE;
TRUNCATE TABLE players CASCADE;
TRUNCATE TABLE teams CASCADE;
TRUNCATE TABLE gleague_teams CASCADE;
TRUNCATE TABLE gleague_games CASCADE;
TRUNCATE TABLE gleague_player_stats CASCADE;
TRUNCATE TABLE coaches CASCADE;
TRUNCATE TABLE gm_profiles CASCADE;
TRUNCATE TABLE profiles CASCADE;
TRUNCATE TABLE contracts CASCADE;
TRUNCATE TABLE contract_extension_offers CASCADE;
TRUNCATE TABLE gm_orders CASCADE;
TRUNCATE TABLE inbox_messages CASCADE;
TRUNCATE TABLE attribute_development CASCADE;
TRUNCATE TABLE injury_log CASCADE;
TRUNCATE TABLE player_interactions CASCADE;
TRUNCATE TABLE transactions CASCADE;
TRUNCATE TABLE awards CASCADE;
TRUNCATE TABLE weekly_highlights CASCADE;
TRUNCATE TABLE power_rankings CASCADE;
TRUNCATE TABLE trade_proposals CASCADE;
TRUNCATE TABLE trade_proposal_teams CASCADE;
TRUNCATE TABLE trade_block CASCADE;
TRUNCATE TABLE fa_offers CASCADE;
TRUNCATE TABLE staff_offers CASCADE;
TRUNCATE TABLE fa_market_offers CASCADE;
TRUNCATE TABLE draft_picks CASCADE;
TRUNCATE TABLE draft_orders CASCADE;
TRUNCATE TABLE draft_results CASCADE;
TRUNCATE TABLE prospects CASCADE;
TRUNCATE TABLE training_slots CASCADE;
TRUNCATE TABLE training_log CASCADE;
TRUNCATE TABLE franchise_config CASCADE;
TRUNCATE TABLE franchise_facilities CASCADE;
TRUNCATE TABLE franchise_finances CASCADE;
TRUNCATE TABLE franchise_transactions CASCADE;
TRUNCATE TABLE arena_concessions CASCADE;
TRUNCATE TABLE arena_sections CASCADE;
TRUNCATE TABLE construction_queue CASCADE;
TRUNCATE TABLE practice_facilities CASCADE;
TRUNCATE TABLE sponsor_contracts CASCADE;
TRUNCATE TABLE sponsor_objective_tracking CASCADE;
TRUNCATE TABLE sponsor_objectives CASCADE;
TRUNCATE TABLE sponsor_pool CASCADE;
TRUNCATE TABLE sponsor_templates CASCADE;
TRUNCATE TABLE sponsor_jersey_images CASCADE;
TRUNCATE TABLE scout_progress CASCADE;
TRUNCATE TABLE scouting_reveals CASCADE;
TRUNCATE TABLE allstar_config CASCADE;
TRUNCATE TABLE allstar_roster CASCADE;
TRUNCATE TABLE allstar_votes CASCADE;
TRUNCATE TABLE playoff_series CASCADE;
TRUNCATE TABLE playoff_games CASCADE;
TRUNCATE TABLE friendly_requests CASCADE;
TRUNCATE TABLE job_applications CASCADE;
TRUNCATE TABLE chat_messages CASCADE;
TRUNCATE TABLE messages CASCADE;
TRUNCATE TABLE articles CASCADE;
TRUNCATE TABLE world_teams CASCADE;
TRUNCATE TABLE referees CASCADE;
TRUNCATE TABLE season_events CASCADE;
TRUNCATE TABLE site_config CASCADE;
TRUNCATE TABLE injury_types CASCADE;
TRUNCATE TABLE player_interaction_types CASCADE;
TRUNCATE TABLE season_config CASCADE;
-- jersey_sales_reports/marketing_campaigns nao tem copia de seguranca (ficam
-- sempre vazias no RESET, por desenho, tal como awards)
TRUNCATE TABLE jersey_sales_reports CASCADE;
TRUNCATE TABLE marketing_campaigns CASCADE;

-- FASE 2: restaurar tudo a partir do Ponto de Origem
INSERT INTO box_scores SELECT * FROM box_scores_preteste;
INSERT INTO play_by_play SELECT * FROM play_by_play_preteste;
INSERT INTO games SELECT * FROM games_preteste;
INSERT INTO preseason_games SELECT * FROM preseason_games_preteste;
INSERT INTO summer_league_rosters SELECT * FROM summer_league_rosters_preteste;
INSERT INTO summer_league_games SELECT * FROM summer_league_games_preteste;
INSERT INTO summer_league_box_scores SELECT * FROM summer_league_box_scores_preteste;
INSERT INTO player_stats SELECT * FROM player_stats_preteste;
INSERT INTO players SELECT * FROM players_preteste;
INSERT INTO teams SELECT * FROM teams_preteste;
INSERT INTO gleague_teams SELECT * FROM gleague_teams_preteste;
INSERT INTO gleague_games SELECT * FROM gleague_games_preteste;
INSERT INTO gleague_player_stats SELECT * FROM gleague_player_stats_preteste;
INSERT INTO coaches SELECT * FROM coaches_preteste;
INSERT INTO gm_profiles SELECT * FROM gm_profiles_preteste;
INSERT INTO profiles SELECT * FROM profiles_preteste;
INSERT INTO contracts SELECT * FROM contracts_preteste;
INSERT INTO contract_extension_offers SELECT * FROM contract_extension_offers_preteste;
INSERT INTO gm_orders SELECT * FROM gm_orders_preteste;
INSERT INTO inbox_messages SELECT * FROM inbox_messages_preteste;
INSERT INTO attribute_development SELECT * FROM attribute_development_preteste;
INSERT INTO injury_log SELECT * FROM injury_log_preteste;
INSERT INTO player_interactions SELECT * FROM player_interactions_preteste;
INSERT INTO transactions SELECT * FROM transactions_preteste;
INSERT INTO awards SELECT * FROM awards_preteste;
INSERT INTO weekly_highlights SELECT * FROM weekly_highlights_preteste;
INSERT INTO power_rankings SELECT * FROM power_rankings_preteste;
INSERT INTO trade_proposals SELECT * FROM trade_proposals_preteste;
INSERT INTO trade_proposal_teams SELECT * FROM trade_proposal_teams_preteste;
INSERT INTO trade_block SELECT * FROM trade_block_preteste;
INSERT INTO fa_offers SELECT * FROM fa_offers_preteste;
INSERT INTO staff_offers SELECT * FROM staff_offers_preteste;
INSERT INTO fa_market_offers SELECT * FROM fa_market_offers_preteste;
INSERT INTO draft_picks SELECT * FROM draft_picks_preteste;
INSERT INTO draft_orders SELECT * FROM draft_orders_preteste;
INSERT INTO draft_results SELECT * FROM draft_results_preteste;
INSERT INTO prospects SELECT * FROM prospects_preteste;
INSERT INTO training_slots SELECT * FROM training_slots_preteste;
INSERT INTO training_log SELECT * FROM training_log_preteste;
INSERT INTO franchise_config SELECT * FROM franchise_config_preteste;
INSERT INTO franchise_facilities SELECT * FROM franchise_facilities_preteste;
INSERT INTO franchise_finances SELECT * FROM franchise_finances_preteste;
INSERT INTO franchise_transactions SELECT * FROM franchise_transactions_preteste;
INSERT INTO arena_concessions SELECT * FROM arena_concessions_preteste;
INSERT INTO arena_sections SELECT * FROM arena_sections_preteste;
INSERT INTO construction_queue SELECT * FROM construction_queue_preteste;
INSERT INTO practice_facilities SELECT * FROM practice_facilities_preteste;
INSERT INTO sponsor_contracts SELECT * FROM sponsor_contracts_preteste;
INSERT INTO sponsor_objective_tracking SELECT * FROM sponsor_objective_tracking_preteste;
INSERT INTO sponsor_objectives SELECT * FROM sponsor_objectives_preteste;
INSERT INTO sponsor_pool SELECT * FROM sponsor_pool_preteste;
INSERT INTO sponsor_templates SELECT * FROM sponsor_templates_preteste;
INSERT INTO sponsor_jersey_images SELECT * FROM sponsor_jersey_images_preteste;
INSERT INTO scout_progress SELECT * FROM scout_progress_preteste;
INSERT INTO scouting_reveals SELECT * FROM scouting_reveals_preteste;
INSERT INTO allstar_config SELECT * FROM allstar_config_preteste;
INSERT INTO allstar_roster SELECT * FROM allstar_roster_preteste;
INSERT INTO allstar_votes SELECT * FROM allstar_votes_preteste;
INSERT INTO playoff_series SELECT * FROM playoff_series_preteste;
INSERT INTO playoff_games SELECT * FROM playoff_games_preteste;
INSERT INTO friendly_requests SELECT * FROM friendly_requests_preteste;
INSERT INTO job_applications SELECT * FROM job_applications_preteste;
INSERT INTO chat_messages SELECT * FROM chat_messages_preteste;
INSERT INTO messages SELECT * FROM messages_preteste;
INSERT INTO articles SELECT * FROM articles_preteste;
INSERT INTO world_teams SELECT * FROM world_teams_preteste;
INSERT INTO referees SELECT * FROM referees_preteste;
INSERT INTO season_events SELECT * FROM season_events_preteste;
INSERT INTO site_config SELECT * FROM site_config_preteste;
INSERT INTO injury_types SELECT * FROM injury_types_preteste;
INSERT INTO player_interaction_types SELECT * FROM player_interaction_types_preteste;
INSERT INTO season_config SELECT * FROM season_config_preteste;

SET session_replication_role = DEFAULT;

SELECT 'RESET COMPLETO - voltaste ao ponto de partida!' as resultado;