'use client'
import { useTranslation } from '@/components/I18nProvider'

export default function OrdersRulesPage() {
  const { t } = useTranslation()
  const isPT = t('common.save') === 'Guardar'

  const sections = isPT ? [
    { title:'Rotação', color:'#1d4ed8', icon:'📋', rules:['Cada uma das 5 posições (Base, Escolta, Ala, Ala-Poste, Poste) tem 3 slots: Titular, 1º Suplente e 2º Suplente.','Atribui um jogador e minutos a cada slot. O total de minutos por posição tem de ser exatamente 48 — a barra fica verde quando atinges 48/48.','Um jogador só pode ser atribuído a posições compatíveis com o seu perfil.'] },
    { title:'Função com Bola por Jogador', color:'#c2410c', icon:'🏀', rules:['Independente dos minutos — define como cada jogador usa a bola quando a tem: Dominante, Equilibrado, ou Sem Bola.','Jogadores Dominantes controlam a maioria das posses. Jogadores Sem Bola movem-se sem a bola e finalizam jogadas criadas por outros.','Esta definição é sobre estilo de jogo, não sobre quem termina as jogadas de ataque.'] },
    { title:'Prioridades Ofensivas', color:'#b45309', icon:'🎯', rules:['Define a 1ª, 2ª e 3ª opção de ataque — os jogadores que recebem a bola com mais frequência em situações de meia-court.','Trata-se de quem finaliza as jogadas, não de quem controla a bola.'] },
    { title:'Táticas', color:'#15803d', icon:'🧠', rules:['Jogador de Clutch: recebe a bola nos últimos 2 minutos em jogos decididos por 5 pontos ou menos.','Ritmo (50–100): controla o quão rápido a equipa joga. Ritmo alto = mais posses por jogo, mas também mais fadiga e mais risco de lesão.','Taxa de 3 Pontos (0–80%): percentagem de posses terminadas com lançamento de 3. Média NBA ronda os 38%.','Estilo Ofensivo e Estilo Defensivo: têm agora impacto real no jogo — ver a secção "Matchups Táticos" abaixo.'] },
    { title:'Matchups Táticos', color:'#0e7490', icon:'⚔️', rules:['Cada Estilo Ofensivo tem um Estilo Defensivo que o trava bem e outro que sofre contra ele — nenhuma defesa é a melhor contra tudo.','Individual (Man) trava bem o Motion Offense (não há um único desequilíbrio a explorar) mas sofre contra o Isolamento (exatamente o duelo 1x1 que o Isolamento procura).','Zona 2-3 sufoca o Jogo de Poste e o Pick & Roll (satura o garrafão) mas deixa lançadores livres contra o Motion Offense.','Pressing Total cria caos mas é a pior opção contra o Contra-Ataque e o Jogo de Poste (tira defesores do garrafão).','Defesa Fechada (Pack the Paint) sufoca o Isolamento e o Contra-Ataque mas cede espaço ao Pick & Roll e ao Jogo de Poste.','O Ritmo também conta: Contra-Ataque e Pressing Total quer ritmo alto; Isolamento, Jogo de Poste e Defesa Fechada querem ritmo baixo. Motion, Pick & Roll, Individual e Zona funcionam bem a qualquer ritmo.','A capacidade de Ajuste Ofensivo e Ajuste Defensivo do teu Head Coach amplifica as vantagens e reduz as desvantagens destes matchups — um bom coach tira mais proveito de um bom encaixe tático e sofre menos com um mau.'] },
    { title:'Double Team', color:'#7c2d12', icon:'🎯', rules:['Escolhe o jogador mais perigoso da equipa adversária dessa semana para dobrar a marcação (disponível na página de Ordens Semanais, mostra automaticamente o plantel do adversário agendado).','Reduz muito a pontaria desse jogador e aumenta as suas perdas de bola — mas os companheiros dele ficam com lançamentos mais fáceis, já que a tua defesa fica mais fina no resto do campo.','Risco real: se o jogador escolhido não estiver em campo (banco, em falta, etc.), o Double Team não tem qualquer efeito nessa jogada — escolher mal custa-te a vantagem sem ganhares nada.'] },
    { title:'Intensidade de Treino', color:'#6d28d9', icon:'🏋️', rules:['Cinco níveis: Descanso, Leve, Normal, Intenso, Carga Máxima.','Afecta duas coisas ao mesmo tempo: a recuperação de saúde entre jogos (Descanso +150%, Leve +25%, Normal completa, Intenso −50%, Carga Máxima −75% e risco de lesão) e a velocidade a que os atributos dos jogadores evoluem (Descanso pode mesmo fazer regredir ligeiramente, Normal é o ritmo padrão, Carga Máxima quase duplica o ritmo de evolução).','Intensidade mais alta acelera a evolução dos jogadores mas reduz a recuperação entre jogos — é sempre uma troca.'] },
  ] : [
    { title:'Depth Chart', color:'#1d4ed8', icon:'📋', rules:['Each of the 5 positions (PG, SG, SF, PF, C) has 3 slots: Starter, 1st Sub, and 2nd Sub.','Assign a player and minutes to each slot. Total minutes per position must equal exactly 48 — the progress bar turns green at 48/48.','A player can only be assigned to compatible positions for their role.'] },
    { title:'Ball Role per Player', color:'#c2410c', icon:'🏀', rules:['Independent from minutes — this defines how each player uses the ball: Ball Dominant, Balanced, or Off-Ball.','Ball Dominant players control most possessions. Off-Ball players move without the ball and finish plays created by others.','This is about playstyle, not who finishes scoring plays.'] },
    { title:'Offensive Priorities', color:'#b45309', icon:'🎯', rules:['Set your 1st, 2nd, and 3rd scoring options — the players who receive the ball most often in half-court situations.','This is about who finishes plays, not who controls the ball.'] },
    { title:'Tactics', color:'#15803d', icon:'🧠', rules:['Clutch Player: gets the ball in the final 2 minutes in games decided by 5 points or fewer.','Pace (50–100): controls how fast your team plays. High pace = more possessions per game, but also more fatigue and more injury risk.','Three-Point Rate (0–80%): the percentage of possessions ending in a 3-point attempt. NBA average is ~38%.','Attack Style and Defense Style: now have a real effect on the game — see the "Tactical Matchups" section below.'] },
    { title:'Tactical Matchups', color:'#0e7490', icon:'⚔️', rules:['Every Attack Style has a Defense Style that shuts it down and one that struggles against it — no defense is best against everything.','Man-to-Man shuts down Motion Offense (no single mismatch to exploit) but gets exposed by Isolation (exactly the 1-on-1 test Iso wants).','Zone 2-3 smothers Post-Up and Pick & Roll (clogs the paint) but leaves shooters open against Motion Offense\'s ball movement.','Full-Court Press creates chaos but is worst against Fast Break and Post-Up (it pulls defenders away from the paint).','Pack the Paint smothers Isolation and Fast Break drives but concedes the space Pick & Roll and Post-Up want.','Pace matters too: Fast Break and Full-Court Press want a high tempo; Isolation, Post-Up, and Pack the Paint want a slow one. Motion, Pick & Roll, Man-to-Man, and Zone work fine at any pace.','Your Head Coach\'s Offensive and Defensive Adjustment ratings amplify a good matchup and soften a bad one — a strong coach gets more out of a favorable tactical fit and suffers less from an unfavorable one.'] },
    { title:'Double Team', color:'#7c2d12', icon:'🎯', rules:['Pick the opposing team\'s most dangerous player for the week to double-team (available on the Weekly Orders page, which automatically shows that week\'s scheduled opponent\'s roster).','Sharply reduces that player\'s shooting and raises his turnovers — but his teammates get easier looks, since the rest of your defense is stretched thinner.','Real risk: if the player you picked isn\'t actually on the floor (benched, in foul trouble, etc.), the Double Team has no effect at all that possession — picking wrong costs you the trade-off for nothing.'] },
    { title:'Training Intensity', color:'#6d28d9', icon:'🏋️', rules:['Five levels: Rest, Light, Normal, Intense, Max Load.','Affects two things at once: health recovery between games (Rest +150%, Light +25%, Normal full regen, Intense −50%, Max Load −75% and injury risk) and how fast player attributes actually develop (Rest can even cause a slight regression, Normal is the baseline pace, Max Load nearly doubles development speed).','Higher intensity speeds up player development but reduces recovery between games — it\'s always a trade-off.'] },
  ]

  return (
    <div style={{ maxWidth:800, margin:'0 auto', padding:'24px 16px' }}>
      <h1 style={{ fontSize:24, fontWeight:900, color:'#1a1512', margin:0, marginBottom:6 }}>📋 {t('ordersGuide.title')}</h1>
      <p style={{ fontSize:13, color:'#8a8279', marginBottom:24 }}>{t('ordersGuide.subtitle')}</p>
      <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
        {sections.map(section => (
          <div key={section.title} style={{ background:'#faf8f5', border:'1px solid #d4cdc5', borderTop:`3px solid ${section.color}`, borderRadius:12, padding:'16px 18px' }}>
            <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:10 }}>
              <span style={{ fontSize:18 }}>{section.icon}</span>
              <span style={{ fontSize:14, fontWeight:700, color:section.color }}>{section.title}</span>
            </div>
            <ul style={{ margin:0, paddingLeft:18, display:'flex', flexDirection:'column', gap:6 }}>
              {section.rules.map((r,i) => <li key={i} style={{ fontSize:13, color:'#5c554e', lineHeight:1.6 }}>{r}</li>)}
            </ul>
          </div>
        ))}
      </div>
      <div style={{ marginTop:20, padding:'16px 18px', borderRadius:12, background:'#dbeafe', border:'1px solid #93c5fd' }}>
        <div style={{ fontSize:12, color:'#1d4ed8', lineHeight:1.7 }}>
          {isPT ? 'Cada posição precisa de exatamente 48 minutos · Função com Bola ≠ Prioridade Ofensiva · Estilo Ofensivo vs Defensivo é um jogo de pedra-papel-tesoura real · Ritmo também conta para o encaixe tático · Double Team condiciona a estrela adversária mas liberta os restantes · Head Coach amplifica/reduz os matchups · Intensidade de treino troca recuperação de saúde por velocidade de evolução.' : 'Each position needs exactly 48 minutes · Ball Role ≠ Offensive Priority · Attack vs Defense Style is a real rock-paper-scissors matchup · Pace matters for the tactical fit too · Double Team locks down the opposing star but frees his teammates · Head Coach amplifies/softens the matchups · Training Intensity trades health recovery for development speed.'}
        </div>
      </div>
    </div>
  )
}
