'use client'
import { useTranslation } from '@/components/I18nProvider'

export default function OrdersRulesPage() {
  const { t } = useTranslation()
  const isPT = t('common.save') === 'Guardar'

  const sections = isPT ? [
    { title:'Rotação', color:'#1d4ed8', icon:'📋', rules:['Cada uma das 5 posições (Base, Escolta, Ala, Ala-Poste, Poste) tem 3 slots: Titular, 1º Suplente e 2º Suplente.','Atribui um jogador e minutos a cada slot. O total de minutos por posição tem de ser exatamente 48 — a barra fica verde quando atinges 48/48.','Um jogador só pode ser atribuído a posições compatíveis com o seu perfil.'] },
    { title:'Função com Bola por Jogador', color:'#c2410c', icon:'🏀', rules:['Independente dos minutos — define como cada jogador usa a bola quando a tem: Dominante, Equilibrado, ou Sem Bola.','Dominante: esse jogador recebe mesmo mais bola — sobe cerca de 20% a frequência com que a jogada passa por ele. Sem Bola: em troca de não criar o próprio lançamento, ganha pontaria extra especificamente em lançamentos de 3 (jogo de posição, catch-and-shoot). Equilibrado: sem alteração, o comportamento padrão de sempre.','Esta definição é independente da Prioridade Ofensiva — podes ter um jogador Dominante que não é a 1ª opção de finalização.'] },
    { title:'Prioridades Ofensivas', color:'#b45309', icon:'🎯', rules:['Define a 1ª, 2ª e 3ª opção de ataque — os jogadores que recebem a bola com mais frequência em situações de meia-court. Testado: um jogador sem prioridade fica com ~20% dos lançamentos da equipa; a 1ª opção sobe para ~33%.','Trata-se de quem finaliza as jogadas, não de quem controla a bola.','Uma "estrela" que não coloques na lista não recebe nenhum bónus por ser suposta ser boa — só conta o que o atributo Usage dela já garante sozinho.'] },
    { title:'Táticas', color:'#15803d', icon:'🧠', rules:['Jogador de Clutch: recebe a bola nos últimos 2 minutos em jogos decididos por 5 pontos ou menos (janela maior em jogos decisivos e de rivalidade — ver "Fatores do Jogo" abaixo).','Ritmo (50–100): controla o quão rápido a equipa joga. Ritmo alto = mais posses por jogo, mas também mais fadiga e mais risco de lesão.','Taxa de 3 Pontos (0–80%): percentagem de posses terminadas com lançamento de 3. Média NBA ronda os 38%.','Estilo Ofensivo e Estilo Defensivo: têm agora impacto real no jogo — ver a secção "Matchups Táticos" abaixo.'] },
    { title:'Fatores do Jogo', color:'#9333ea', icon:'🏟️', rules:['Fator casa: a equipa da casa tem sempre uma pequena vantagem estrutural, que cresce consoante a assistência esperada — quanto mais cheio o pavilhão, maior o efeito.','Efeito de Público: o atributo Crowd Effect de cada jogador (de ambas as equipas) faz-lhe subir ou descer o rendimento consoante o pavilhão está mais ou menos cheio — há jogadores que se alimentam de um público ruidoso, seja em casa ou fora.','Jogo de Rivalidade: a pressão do "Clutch" deixa de estar limitada aos últimos 2 minutos — passa a contar no 4º período inteiro.','Jogo Decisivo: playoffs contam sempre. Na regular season, as posições 7ª-10ª da conferência SÃO a zona do Play-In Tournament — contam sempre como decisivas. As posições 4ª-6ª (a lutar para evitar cair no Play-In) e 11ª-13ª (a lutar para lá chegar) também contam. Nesses jogos a janela de Clutch alarga (últimos 4 min, jogos até 8 pontos) e o atributo Pressure pesa ainda mais, para o bem e para o mal.'] },
    { title:'Matchups Táticos', color:'#0e7490', icon:'⚔️', rules:['Cada Estilo Ofensivo tem um Estilo Defensivo que o trava bem e outro que sofre contra ele — nenhuma defesa é a melhor contra tudo.','O Estilo Ofensivo agora também muda mesmo o TIPO de lançamento: Jogo de Poste gera muito mais lançamentos perto do cesto/poste; Contra-Ataque quase só lançamentos rápidos perto do cesto; Isolamento favorece lançamentos de meia-distância criados a solo; Pick & Roll mistura poste e meia-distância; Motion é o equilíbrio de sempre.','Individual (Man) trava bem o Motion Offense (não há um único desequilíbrio a explorar) mas sofre contra o Isolamento (exatamente o duelo 1x1 que o Isolamento procura).','Zona 2-3 sufoca o Jogo de Poste e o Pick & Roll (satura o garrafão) mas deixa lançadores livres contra o Motion Offense.','Pressing Total cria caos mas é a pior opção contra o Contra-Ataque e o Jogo de Poste (tira defesores do garrafão).','Defesa Fechada (Pack the Paint) sufoca o Isolamento e o Contra-Ataque mas cede espaço ao Pick & Roll e ao Jogo de Poste.','O Ritmo também conta: Contra-Ataque e Pressing Total quer ritmo alto; Isolamento, Jogo de Poste e Defesa Fechada querem ritmo baixo. Motion, Pick & Roll, Individual e Zona funcionam bem a qualquer ritmo.','A capacidade de Ajuste Ofensivo e Ajuste Defensivo do teu Head Coach amplifica as vantagens e reduz as desvantagens destes matchups — um bom coach tira mais proveito de um bom encaixe tático e sofre menos com um mau.'] },
    { title:'Double Team', color:'#7c2d12', icon:'🎯', rules:['Escolhe um jogador para dobrar a marcação — a página de Ordens Semanais mostra automaticamente os plantéis de TODOS os adversários que vais defrontar essa semana (jogas vários jogos por semana, normalmente contra equipas diferentes), agrupados por adversário.','Tal como o Ritmo, a Taxa de 3 e os Estilos, é uma escolha semanal única que se aplica a todos os teus jogos dessa semana — mas só tem efeito real no jogo específico contra a equipa real desse jogador. Nos outros jogos da semana simplesmente não faz nada, sem penalização.','Reduz muito a pontaria desse jogador e aumenta as suas perdas de bola — mas os companheiros dele ficam com lançamentos mais fáceis, já que a tua defesa fica mais fina no resto do campo.','Risco real: se o jogador escolhido não estiver em campo nesse jogo (banco, em falta, etc.), o Double Team não tem qualquer efeito — escolher mal custa-te a vantagem sem ganhares nada.'] },
    { title:'Intensidade de Treino', color:'#6d28d9', icon:'🏋️', rules:['Cinco níveis: Descanso, Leve, Normal, Intenso, Carga Máxima.','Afecta duas coisas ao mesmo tempo: a recuperação de saúde entre jogos (Descanso +150%, Leve +25%, Normal completa, Intenso −50%, Carga Máxima −75% e risco de lesão) e a velocidade a que os atributos dos jogadores evoluem (Descanso pode mesmo fazer regredir ligeiramente, Normal é o ritmo padrão, Carga Máxima quase duplica o ritmo de evolução).','Intensidade mais alta acelera a evolução dos jogadores mas reduz a recuperação entre jogos — é sempre uma troca.'] },
  ] : [
    { title:'Depth Chart', color:'#1d4ed8', icon:'📋', rules:['Each of the 5 positions (PG, SG, SF, PF, C) has 3 slots: Starter, 1st Sub, and 2nd Sub.','Assign a player and minutes to each slot. Total minutes per position must equal exactly 48 — the progress bar turns green at 48/48.','A player can only be assigned to compatible positions for their role.'] },
    { title:'Ball Role per Player', color:'#c2410c', icon:'🏀', rules:['Independent from minutes — this defines how each player uses the ball: Ball Dominant, Balanced, or Off-Ball.','Ball Dominant: genuinely gets more touches — raises how often the ball runs through them by about 20%. Off-Ball: in exchange for not creating his own shot, gets a real accuracy bump specifically on 3-point attempts (spot-up, catch-and-shoot). Balanced: no change, today\'s default behavior.','This is independent from Offensive Priority — you can have a Ball Dominant player who isn\'t your 1st scoring option.'] },
    { title:'Offensive Priorities', color:'#b45309', icon:'🎯', rules:['Set your 1st, 2nd, and 3rd scoring options — the players who receive the ball most often in half-court situations. Tested: an unlisted player gets ~20% of team shot attempts; the 1st option rises to ~33%.','This is about who finishes plays, not who controls the ball.','A "star" you don\'t list gets no bonus for supposedly being good — only whatever his Usage attribute already earns him on its own.'] },
    { title:'Tactics', color:'#15803d', icon:'🧠', rules:['Clutch Player: gets the ball in the final 2 minutes in games decided by 5 points or fewer (a wider window in decisive and rivalry games — see "Game Factors" below).','Pace (50–100): controls how fast your team plays. High pace = more possessions per game, but also more fatigue and more injury risk.','Three-Point Rate (0–80%): the percentage of possessions ending in a 3-point attempt. NBA average is ~38%.','Attack Style and Defense Style: now have a real effect on the game — see the "Tactical Matchups" section below.'] },
    { title:'Game Factors', color:'#9333ea', icon:'🏟️', rules:['Home Court: the home team always gets a small structural edge, which grows with expected attendance — the fuller the arena, the bigger the effect.','Crowd Effect: each player\'s own Crowd Effect attribute (on either team) shifts their performance up or down depending on how full the arena is — some players feed off a loud crowd, home or away.','Rivalry Game: "Clutch" pressure is no longer limited to the final 2 minutes — it applies across the entire 4th quarter.','Decisive Game: playoffs always count. In the regular season, conference ranks 7th-10th ARE the Play-In Tournament zone — always decisive. Ranks 4th-6th (fighting to avoid falling into it) and 11th-13th (fighting to climb into it) count too. In these games the Clutch window widens (final 4 minutes, games within 8 points) and the Pressure attribute matters even more, for better or worse.'] },
    { title:'Tactical Matchups', color:'#0e7490', icon:'⚔️', rules:['Every Attack Style has a Defense Style that shuts it down and one that struggles against it — no defense is best against everything.','Attack Style now genuinely changes the TYPE of shot too: Post-Up generates far more shots near the rim/post; Fast Break is almost all quick looks at the basket; Isolation favors self-created mid-range shots; Pick & Roll blends post and mid-range; Motion stays the usual balanced mix.','Man-to-Man shuts down Motion Offense (no single mismatch to exploit) but gets exposed by Isolation (exactly the 1-on-1 test Iso wants).','Zone 2-3 smothers Post-Up and Pick & Roll (clogs the paint) but leaves shooters open against Motion Offense\'s ball movement.','Full-Court Press creates chaos but is worst against Fast Break and Post-Up (it pulls defenders away from the paint).','Pack the Paint smothers Isolation and Fast Break drives but concedes the space Pick & Roll and Post-Up want.','Pace matters too: Fast Break and Full-Court Press want a high tempo; Isolation, Post-Up, and Pack the Paint want a slow one. Motion, Pick & Roll, Man-to-Man, and Zone work fine at any pace.','Your Head Coach\'s Offensive and Defensive Adjustment ratings amplify a good matchup and soften a bad one — a strong coach gets more out of a favorable tactical fit and suffers less from an unfavorable one.'] },
    { title:'Double Team', color:'#7c2d12', icon:'🎯', rules:['Pick a player to double-team — the Weekly Orders page automatically shows the rosters of EVERY opponent you\'ll face that week (you play several games per week, usually against different teams), grouped by opponent.','Like Pace, Three-Point Rate, and the Styles, it\'s one weekly choice that applies to every game that week — but it only actually does anything in the specific game against that player\'s real team. In your other games that week it simply does nothing, with no penalty.','Sharply reduces that player\'s shooting and raises his turnovers — but his teammates get easier looks, since the rest of your defense is stretched thinner.','Real risk: if the player you picked isn\'t on the floor in that game (benched, in foul trouble, etc.), the Double Team has no effect at all — picking wrong costs you the trade-off for nothing.'] },
    { title:'Training Intensity', color:'#6d28d9', icon:'🏋️', rules:['Five levels: Rest, Light, Normal, Intense, Max Load.','Affects two things at once: health recovery between games (Rest +150%, Light +25%, Normal full regen, Intense −50%, Max Load −75% and injury risk) and how fast player attributes actually develop (Rest can even cause a slight regression, Normal is the baseline pace, Max Load nearly doubles development speed).','Higher intensity speeds up player development but reduces recovery between games — it\'s always a trade-off.'] },
  ]

  return (
    <div style={{ maxWidth:800, margin:'0 auto', padding:'24px 16px' }}>
      <h1 style={{ fontSize:24, fontWeight:900, color:'#1a1512', margin:0, marginBottom:6 }}>📋 {t('ordersGuide.title')}</h1>
      <p style={{ fontSize:13, color:'#8a8279', marginBottom:24 }}>{t('ordersGuide.subtitle')}</p>
      <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
        {sections.map(section => (
          <div key={section.title} style={{ background:'#faf8f5', border:'1px solid #d4cdc5', borderTop:`3px solid ${section.color}`, borderRadius:12, padding:'16px 18px' }}>
            <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:10 }}>
              <span style={{ fontSize:18 }}>{section.icon}</span>
              <span style={{ fontSize:14, fontWeight:700, color:section.color }}>{section.title}</span>
            </div>
            <ul style={{ margin:0, paddingLeft:18, display:'flex', flexDirection:'column', gap:6 }}>
              {section.rules.map((r,i) => <li key={i} style={{ fontSize:13, color:'#5c554e', lineHeight:1.6 }}>{r}</li>)}
            </ul>
          </div>
        ))}
      </div>
      <div style={{ marginTop:20, padding:'16px 18px', borderRadius:12, background:'#dbeafe', border:'1px solid #93c5fd' }}>
        <div style={{ fontSize:12, color:'#1d4ed8', lineHeight:1.7 }}>
          {isPT ? 'Prioridade Ofensiva: ~20% sem lista → ~33% na 1ª opção · Ball Role Dominante/Sem Bola tem efeito real · Estilo Ofensivo muda o tipo de lançamento, não só o matchup · Double Team condiciona a estrela adversária mas liberta os restantes · Fator casa cresce com a assistência · Posições 7-10 = zona do Play-In, sempre decisiva.' : 'Offensive Priority: ~20% unlisted → ~33% as 1st option · Dominant/Off-Ball Ball Role has a real effect · Attack Style changes shot type, not just the matchup · Double Team locks down the opposing star but frees his teammates · Home court grows with attendance · Ranks 7-10 are the Play-In zone, always decisive.'}
        </div>
      </div>
    </div>
  )
}
